import type { Metadata } from 'next'
import { Krub } from 'next/font/google'
import './globals.css'

// Include in project
import { MainLayout } from '@/components'

const thai = Krub({
  variable: '--font-thai',
  subsets: ['latin', 'thai'],
  weight: ['500'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${thai.variable} antialiased`}>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  )
}
